// Code generated by sequencegenerator; DO NOT EDIT.

package input

type seq struct{
    seq   string
    event Event
}

var sequences = []seq{

    // ASCII Chars
    {"!", KeyboardEvent{Code: "!",Key: "!"}}, // !
    {"\"", KeyboardEvent{Code: "\"",Key: "\""}}, // "
    {"#", KeyboardEvent{Code: "#",Key: "#"}}, // #
    {"$", KeyboardEvent{Code: "$",Key: "$"}}, // $
    {"%", KeyboardEvent{Code: "%",Key: "%"}}, // %
    {"&", KeyboardEvent{Code: "&",Key: "&"}}, // &
    {"'", KeyboardEvent{Code: "'",Key: "'"}}, // '
    {"(", KeyboardEvent{Code: "(",Key: "("}}, // (
    {")", KeyboardEvent{Code: ")",Key: ")"}}, // )
    {"*", KeyboardEvent{Code: "*",Key: "*"}}, // *
    {"+", KeyboardEvent{Code: "+",Key: "+"}}, // +
    {",", KeyboardEvent{Code: ",",Key: ","}}, // ,
    {"-", KeyboardEvent{Code: "-",Key: "-"}}, // -
    {".", KeyboardEvent{Code: ".",Key: "."}}, // .
    {"/", KeyboardEvent{Code: "/",Key: "/"}}, // /
    {"0", KeyboardEvent{Code: "0",Key: "0"}}, // 0
    {"1", KeyboardEvent{Code: "1",Key: "1"}}, // 1
    {"2", KeyboardEvent{Code: "2",Key: "2"}}, // 2
    {"3", KeyboardEvent{Code: "3",Key: "3"}}, // 3
    {"4", KeyboardEvent{Code: "4",Key: "4"}}, // 4
    {"5", KeyboardEvent{Code: "5",Key: "5"}}, // 5
    {"6", KeyboardEvent{Code: "6",Key: "6"}}, // 6
    {"7", KeyboardEvent{Code: "7",Key: "7"}}, // 7
    {"8", KeyboardEvent{Code: "8",Key: "8"}}, // 8
    {"9", KeyboardEvent{Code: "9",Key: "9"}}, // 9
    {":", KeyboardEvent{Code: ":",Key: ":"}}, // :
    {";", KeyboardEvent{Code: ";",Key: ";"}}, // ;
    {"<", KeyboardEvent{Code: "<",Key: "<"}}, // <
    {"=", KeyboardEvent{Code: "=",Key: "="}}, // =
    {">", KeyboardEvent{Code: ">",Key: ">"}}, // >
    {"?", KeyboardEvent{Code: "?",Key: "?"}}, // ?
    {"@", KeyboardEvent{Code: "@",Key: "@"}}, // @
    {"A", KeyboardEvent{Code: "A",Key: "A"}}, // A
    {"B", KeyboardEvent{Code: "B",Key: "B"}}, // B
    {"C", KeyboardEvent{Code: "C",Key: "C"}}, // C
    {"D", KeyboardEvent{Code: "D",Key: "D"}}, // D
    {"E", KeyboardEvent{Code: "E",Key: "E"}}, // E
    {"F", KeyboardEvent{Code: "F",Key: "F"}}, // F
    {"G", KeyboardEvent{Code: "G",Key: "G"}}, // G
    {"H", KeyboardEvent{Code: "H",Key: "H"}}, // H
    {"I", KeyboardEvent{Code: "I",Key: "I"}}, // I
    {"J", KeyboardEvent{Code: "J",Key: "J"}}, // J
    {"K", KeyboardEvent{Code: "K",Key: "K"}}, // K
    {"L", KeyboardEvent{Code: "L",Key: "L"}}, // L
    {"M", KeyboardEvent{Code: "M",Key: "M"}}, // M
    {"N", KeyboardEvent{Code: "N",Key: "N"}}, // N
    {"O", KeyboardEvent{Code: "O",Key: "O"}}, // O
    {"P", KeyboardEvent{Code: "P",Key: "P"}}, // P
    {"Q", KeyboardEvent{Code: "Q",Key: "Q"}}, // Q
    {"R", KeyboardEvent{Code: "R",Key: "R"}}, // R
    {"S", KeyboardEvent{Code: "S",Key: "S"}}, // S
    {"T", KeyboardEvent{Code: "T",Key: "T"}}, // T
    {"U", KeyboardEvent{Code: "U",Key: "U"}}, // U
    {"V", KeyboardEvent{Code: "V",Key: "V"}}, // V
    {"W", KeyboardEvent{Code: "W",Key: "W"}}, // W
    {"X", KeyboardEvent{Code: "X",Key: "X"}}, // X
    {"Y", KeyboardEvent{Code: "Y",Key: "Y"}}, // Y
    {"Z", KeyboardEvent{Code: "Z",Key: "Z"}}, // Z
    {"[", KeyboardEvent{Code: "[",Key: "["}}, // [
    {"\\", KeyboardEvent{Code: "\\",Key: "\\"}}, // \
    {"]", KeyboardEvent{Code: "]",Key: "]"}}, // ]
    {"^", KeyboardEvent{Code: "^",Key: "^"}}, // ^
    {"_", KeyboardEvent{Code: "_",Key: "_"}}, // _
    {"`", KeyboardEvent{Code: "`",Key: "`"}}, // `
    {"a", KeyboardEvent{Code: "a",Key: "a"}}, // a
    {"b", KeyboardEvent{Code: "b",Key: "b"}}, // b
    {"c", KeyboardEvent{Code: "c",Key: "c"}}, // c
    {"d", KeyboardEvent{Code: "d",Key: "d"}}, // d
    {"e", KeyboardEvent{Code: "e",Key: "e"}}, // e
    {"f", KeyboardEvent{Code: "f",Key: "f"}}, // f
    {"g", KeyboardEvent{Code: "g",Key: "g"}}, // g
    {"h", KeyboardEvent{Code: "h",Key: "h"}}, // h
    {"i", KeyboardEvent{Code: "i",Key: "i"}}, // i
    {"j", KeyboardEvent{Code: "j",Key: "j"}}, // j
    {"k", KeyboardEvent{Code: "k",Key: "k"}}, // k
    {"l", KeyboardEvent{Code: "l",Key: "l"}}, // l
    {"m", KeyboardEvent{Code: "m",Key: "m"}}, // m
    {"n", KeyboardEvent{Code: "n",Key: "n"}}, // n
    {"o", KeyboardEvent{Code: "o",Key: "o"}}, // o
    {"p", KeyboardEvent{Code: "p",Key: "p"}}, // p
    {"q", KeyboardEvent{Code: "q",Key: "q"}}, // q
    {"r", KeyboardEvent{Code: "r",Key: "r"}}, // r
    {"s", KeyboardEvent{Code: "s",Key: "s"}}, // s
    {"t", KeyboardEvent{Code: "t",Key: "t"}}, // t
    {"u", KeyboardEvent{Code: "u",Key: "u"}}, // u
    {"v", KeyboardEvent{Code: "v",Key: "v"}}, // v
    {"w", KeyboardEvent{Code: "w",Key: "w"}}, // w
    {"x", KeyboardEvent{Code: "x",Key: "x"}}, // x
    {"y", KeyboardEvent{Code: "y",Key: "y"}}, // y
    {"z", KeyboardEvent{Code: "z",Key: "z"}}, // z
    {"{", KeyboardEvent{Code: "{",Key: "{"}}, // {
    {"|", KeyboardEvent{Code: "|",Key: "|"}}, // |
    {"}", KeyboardEvent{Code: "}",Key: "}"}}, // }
    {"~", KeyboardEvent{Code: "~",Key: "~"}}, // ~

    // Control Keys
    {"\x01", KeyboardEvent{Code: "A", Ctrl: true}}, // Ctrl+A
    {"\x02", KeyboardEvent{Code: "B", Ctrl: true}}, // Ctrl+B
    {"\x03", KeyboardEvent{Code: "C", Ctrl: true}}, // Ctrl+C
    {"\x04", KeyboardEvent{Code: "D", Ctrl: true}}, // Ctrl+D
    {"\x05", KeyboardEvent{Code: "E", Ctrl: true}}, // Ctrl+E
    {"\x06", KeyboardEvent{Code: "F", Ctrl: true}}, // Ctrl+F
    {"\a", KeyboardEvent{Code: "G", Ctrl: true}}, // Ctrl+G
    {"\b", KeyboardEvent{Code: "H", Ctrl: true}}, // Ctrl+H
    {"\t", KeyboardEvent{Code: "I", Ctrl: true}}, // Ctrl+I
    {"\n", KeyboardEvent{Code: "J", Ctrl: true}}, // Ctrl+J
    {"\v", KeyboardEvent{Code: "K", Ctrl: true}}, // Ctrl+K
    {"\f", KeyboardEvent{Code: "L", Ctrl: true}}, // Ctrl+L
    {"\r", KeyboardEvent{Code: "M", Ctrl: true}}, // Ctrl+M
    {"\x0e", KeyboardEvent{Code: "N", Ctrl: true}}, // Ctrl+N
    {"\x0f", KeyboardEvent{Code: "O", Ctrl: true}}, // Ctrl+O
    {"\x10", KeyboardEvent{Code: "P", Ctrl: true}}, // Ctrl+P
    {"\x11", KeyboardEvent{Code: "Q", Ctrl: true}}, // Ctrl+Q
    {"\x12", KeyboardEvent{Code: "R", Ctrl: true}}, // Ctrl+R
    {"\x13", KeyboardEvent{Code: "S", Ctrl: true}}, // Ctrl+S
    {"\x14", KeyboardEvent{Code: "T", Ctrl: true}}, // Ctrl+T
    {"\x15", KeyboardEvent{Code: "U", Ctrl: true}}, // Ctrl+U
    {"\x16", KeyboardEvent{Code: "V", Ctrl: true}}, // Ctrl+V
    {"\x17", KeyboardEvent{Code: "W", Ctrl: true}}, // Ctrl+W
    {"\x18", KeyboardEvent{Code: "X", Ctrl: true}}, // Ctrl+X
    {"\x19", KeyboardEvent{Code: "Y", Ctrl: true}}, // Ctrl+Y
    {"\x1a", KeyboardEvent{Code: "Z", Ctrl: true}}, // Ctrl+Z

    // Alt Keys
    {"\x1b!", KeyboardEvent{Code: "!", Alt: true}}, // Alt+!
    {"\x1b\"", KeyboardEvent{Code: "\"", Alt: true}}, // Alt+"
    {"\x1b#", KeyboardEvent{Code: "#", Alt: true}}, // Alt+#
    {"\x1b$", KeyboardEvent{Code: "$", Alt: true}}, // Alt+$
    {"\x1b%", KeyboardEvent{Code: "%", Alt: true}}, // Alt+%
    {"\x1b&", KeyboardEvent{Code: "&", Alt: true}}, // Alt+&
    {"\x1b'", KeyboardEvent{Code: "'", Alt: true}}, // Alt+'
    {"\x1b(", KeyboardEvent{Code: "(", Alt: true}}, // Alt+(
    {"\x1b)", KeyboardEvent{Code: ")", Alt: true}}, // Alt+)
    {"\x1b*", KeyboardEvent{Code: "*", Alt: true}}, // Alt+*
    {"\x1b+", KeyboardEvent{Code: "+", Alt: true}}, // Alt++
    {"\x1b,", KeyboardEvent{Code: ",", Alt: true}}, // Alt+,
    {"\x1b-", KeyboardEvent{Code: "-", Alt: true}}, // Alt+-
    {"\x1b.", KeyboardEvent{Code: ".", Alt: true}}, // Alt+.
    {"\x1b/", KeyboardEvent{Code: "/", Alt: true}}, // Alt+/
    {"\x1b0", KeyboardEvent{Code: "0", Alt: true}}, // Alt+0
    {"\x1b1", KeyboardEvent{Code: "1", Alt: true}}, // Alt+1
    {"\x1b2", KeyboardEvent{Code: "2", Alt: true}}, // Alt+2
    {"\x1b3", KeyboardEvent{Code: "3", Alt: true}}, // Alt+3
    {"\x1b4", KeyboardEvent{Code: "4", Alt: true}}, // Alt+4
    {"\x1b5", KeyboardEvent{Code: "5", Alt: true}}, // Alt+5
    {"\x1b6", KeyboardEvent{Code: "6", Alt: true}}, // Alt+6
    {"\x1b7", KeyboardEvent{Code: "7", Alt: true}}, // Alt+7
    {"\x1b8", KeyboardEvent{Code: "8", Alt: true}}, // Alt+8
    {"\x1b9", KeyboardEvent{Code: "9", Alt: true}}, // Alt+9
    {"\x1b:", KeyboardEvent{Code: ":", Alt: true}}, // Alt+:
    {"\x1b;", KeyboardEvent{Code: ";", Alt: true}}, // Alt+;
    {"\x1b<", KeyboardEvent{Code: "<", Alt: true}}, // Alt+<
    {"\x1b=", KeyboardEvent{Code: "=", Alt: true}}, // Alt+=
    {"\x1b>", KeyboardEvent{Code: ">", Alt: true}}, // Alt+>
    {"\x1b?", KeyboardEvent{Code: "?", Alt: true}}, // Alt+?
    {"\x1b@", KeyboardEvent{Code: "@", Alt: true}}, // Alt+@
    {"\x1bA", KeyboardEvent{Code: "A", Alt: true}}, // Alt+A
    {"\x1bB", KeyboardEvent{Code: "B", Alt: true}}, // Alt+B
    {"\x1bC", KeyboardEvent{Code: "C", Alt: true}}, // Alt+C
    {"\x1bD", KeyboardEvent{Code: "D", Alt: true}}, // Alt+D
    {"\x1bE", KeyboardEvent{Code: "E", Alt: true}}, // Alt+E
    {"\x1bF", KeyboardEvent{Code: "F", Alt: true}}, // Alt+F
    {"\x1bG", KeyboardEvent{Code: "G", Alt: true}}, // Alt+G
    {"\x1bH", KeyboardEvent{Code: "H", Alt: true}}, // Alt+H
    {"\x1bI", KeyboardEvent{Code: "I", Alt: true}}, // Alt+I
    {"\x1bJ", KeyboardEvent{Code: "J", Alt: true}}, // Alt+J
    {"\x1bK", KeyboardEvent{Code: "K", Alt: true}}, // Alt+K
    {"\x1bL", KeyboardEvent{Code: "L", Alt: true}}, // Alt+L
    {"\x1bM", KeyboardEvent{Code: "M", Alt: true}}, // Alt+M
    {"\x1bN", KeyboardEvent{Code: "N", Alt: true}}, // Alt+N
    {"\x1bO", KeyboardEvent{Code: "O", Alt: true}}, // Alt+O
    {"\x1bP", KeyboardEvent{Code: "P", Alt: true}}, // Alt+P
    {"\x1bQ", KeyboardEvent{Code: "Q", Alt: true}}, // Alt+Q
    {"\x1bR", KeyboardEvent{Code: "R", Alt: true}}, // Alt+R
    {"\x1bS", KeyboardEvent{Code: "S", Alt: true}}, // Alt+S
    {"\x1bT", KeyboardEvent{Code: "T", Alt: true}}, // Alt+T
    {"\x1bU", KeyboardEvent{Code: "U", Alt: true}}, // Alt+U
    {"\x1bV", KeyboardEvent{Code: "V", Alt: true}}, // Alt+V
    {"\x1bW", KeyboardEvent{Code: "W", Alt: true}}, // Alt+W
    {"\x1bX", KeyboardEvent{Code: "X", Alt: true}}, // Alt+X
    {"\x1bY", KeyboardEvent{Code: "Y", Alt: true}}, // Alt+Y
    {"\x1bZ", KeyboardEvent{Code: "Z", Alt: true}}, // Alt+Z
    {"\x1b[", KeyboardEvent{Code: "[", Alt: true}}, // Alt+[
    {"\x1b\\", KeyboardEvent{Code: "\\", Alt: true}}, // Alt+\
    {"\x1b]", KeyboardEvent{Code: "]", Alt: true}}, // Alt+]
    {"\x1b^", KeyboardEvent{Code: "^", Alt: true}}, // Alt+^
    {"\x1b_", KeyboardEvent{Code: "_", Alt: true}}, // Alt+_
    {"\x1b`", KeyboardEvent{Code: "`", Alt: true}}, // Alt+`
    {"\x1ba", KeyboardEvent{Code: "a", Alt: true}}, // Alt+a
    {"\x1bb", KeyboardEvent{Code: "b", Alt: true}}, // Alt+b
    {"\x1bc", KeyboardEvent{Code: "c", Alt: true}}, // Alt+c
    {"\x1bd", KeyboardEvent{Code: "d", Alt: true}}, // Alt+d
    {"\x1be", KeyboardEvent{Code: "e", Alt: true}}, // Alt+e
    {"\x1bf", KeyboardEvent{Code: "f", Alt: true}}, // Alt+f
    {"\x1bg", KeyboardEvent{Code: "g", Alt: true}}, // Alt+g
    {"\x1bh", KeyboardEvent{Code: "h", Alt: true}}, // Alt+h
    {"\x1bi", KeyboardEvent{Code: "i", Alt: true}}, // Alt+i
    {"\x1bj", KeyboardEvent{Code: "j", Alt: true}}, // Alt+j
    {"\x1bk", KeyboardEvent{Code: "k", Alt: true}}, // Alt+k
    {"\x1bl", KeyboardEvent{Code: "l", Alt: true}}, // Alt+l
    {"\x1bm", KeyboardEvent{Code: "m", Alt: true}}, // Alt+m
    {"\x1bn", KeyboardEvent{Code: "n", Alt: true}}, // Alt+n
    {"\x1bo", KeyboardEvent{Code: "o", Alt: true}}, // Alt+o
    {"\x1bp", KeyboardEvent{Code: "p", Alt: true}}, // Alt+p
    {"\x1bq", KeyboardEvent{Code: "q", Alt: true}}, // Alt+q
    {"\x1br", KeyboardEvent{Code: "r", Alt: true}}, // Alt+r
    {"\x1bs", KeyboardEvent{Code: "s", Alt: true}}, // Alt+s
    {"\x1bt", KeyboardEvent{Code: "t", Alt: true}}, // Alt+t
    {"\x1bu", KeyboardEvent{Code: "u", Alt: true}}, // Alt+u
    {"\x1bv", KeyboardEvent{Code: "v", Alt: true}}, // Alt+v
    {"\x1bw", KeyboardEvent{Code: "w", Alt: true}}, // Alt+w
    {"\x1bx", KeyboardEvent{Code: "x", Alt: true}}, // Alt+x
    {"\x1by", KeyboardEvent{Code: "y", Alt: true}}, // Alt+y
    {"\x1bz", KeyboardEvent{Code: "z", Alt: true}}, // Alt+z
    {"\x1b{", KeyboardEvent{Code: "{", Alt: true}}, // Alt+{
    {"\x1b|", KeyboardEvent{Code: "|", Alt: true}}, // Alt+|
    {"\x1b}", KeyboardEvent{Code: "}", Alt: true}}, // Alt+}
    {"\x1b~", KeyboardEvent{Code: "~", Alt: true}}, // Alt+~

    // Control + Alt Keys
    {"\x1b\x01", KeyboardEvent{Code: "A", Alt: true, Ctrl: true}}, // Ctrl+Alt+A
    {"\x1b\x02", KeyboardEvent{Code: "B", Alt: true, Ctrl: true}}, // Ctrl+Alt+B
    {"\x1b\x03", KeyboardEvent{Code: "C", Alt: true, Ctrl: true}}, // Ctrl+Alt+C
    {"\x1b\x04", KeyboardEvent{Code: "D", Alt: true, Ctrl: true}}, // Ctrl+Alt+D
    {"\x1b\x05", KeyboardEvent{Code: "E", Alt: true, Ctrl: true}}, // Ctrl+Alt+E
    {"\x1b\x06", KeyboardEvent{Code: "F", Alt: true, Ctrl: true}}, // Ctrl+Alt+F
    {"\x1b\a", KeyboardEvent{Code: "G", Alt: true, Ctrl: true}}, // Ctrl+Alt+G
    {"\x1b\b", KeyboardEvent{Code: "H", Alt: true, Ctrl: true}}, // Ctrl+Alt+H
    {"\x1b\t", KeyboardEvent{Code: "I", Alt: true, Ctrl: true}}, // Ctrl+Alt+I
    {"\x1b\n", KeyboardEvent{Code: "J", Alt: true, Ctrl: true}}, // Ctrl+Alt+J
    {"\x1b\v", KeyboardEvent{Code: "K", Alt: true, Ctrl: true}}, // Ctrl+Alt+K
    {"\x1b\f", KeyboardEvent{Code: "L", Alt: true, Ctrl: true}}, // Ctrl+Alt+L
    {"\x1b\r", KeyboardEvent{Code: "M", Alt: true, Ctrl: true}}, // Ctrl+Alt+M
    {"\x1b\x0e", KeyboardEvent{Code: "N", Alt: true, Ctrl: true}}, // Ctrl+Alt+N
    {"\x1b\x0f", KeyboardEvent{Code: "O", Alt: true, Ctrl: true}}, // Ctrl+Alt+O
    {"\x1b\x10", KeyboardEvent{Code: "P", Alt: true, Ctrl: true}}, // Ctrl+Alt+P
    {"\x1b\x11", KeyboardEvent{Code: "Q", Alt: true, Ctrl: true}}, // Ctrl+Alt+Q
    {"\x1b\x12", KeyboardEvent{Code: "R", Alt: true, Ctrl: true}}, // Ctrl+Alt+R
    {"\x1b\x13", KeyboardEvent{Code: "S", Alt: true, Ctrl: true}}, // Ctrl+Alt+S
    {"\x1b\x14", KeyboardEvent{Code: "T", Alt: true, Ctrl: true}}, // Ctrl+Alt+T
    {"\x1b\x15", KeyboardEvent{Code: "U", Alt: true, Ctrl: true}}, // Ctrl+Alt+U
    {"\x1b\x16", KeyboardEvent{Code: "V", Alt: true, Ctrl: true}}, // Ctrl+Alt+V
    {"\x1b\x17", KeyboardEvent{Code: "W", Alt: true, Ctrl: true}}, // Ctrl+Alt+W
    {"\x1b\x18", KeyboardEvent{Code: "X", Alt: true, Ctrl: true}}, // Ctrl+Alt+X
    {"\x1b\x19", KeyboardEvent{Code: "Y", Alt: true, Ctrl: true}}, // Ctrl+Alt+Y
    {"\x1b\x1a", KeyboardEvent{Code: "Z", Alt: true, Ctrl: true}}, // Ctrl+Alt+Z

    // Fn and directions
    // Normal
    {"\x1bOP", KeyboardEvent{Code: "F1"}}, // F1
    {"\x1bOQ", KeyboardEvent{Code: "F2"}}, // F2
    {"\x1bOR", KeyboardEvent{Code: "F3"}}, // F3
    {"\x1bOS", KeyboardEvent{Code: "F4"}}, // F4
    {"\x1b[15~", KeyboardEvent{Code: "F5"}}, // F5
    {"\x1b[17~", KeyboardEvent{Code: "F6"}}, // F6
    {"\x1b[18~", KeyboardEvent{Code: "F7"}}, // F7
    {"\x1b[19~", KeyboardEvent{Code: "F8"}}, // F8
    {"\x1b[20~", KeyboardEvent{Code: "F9"}}, // F9
    {"\x1b[21~", KeyboardEvent{Code: "F10"}}, // F10
    {"\x1b[23~", KeyboardEvent{Code: "F11"}}, // F11
    {"\x1b[24~", KeyboardEvent{Code: "F12"}}, // F12
    {"\x1b[5~", KeyboardEvent{Code: "PageUp"}}, // PageUp
    {"\x1b[6~", KeyboardEvent{Code: "PageDown"}}, // PageDown
    {"\x1b[H", KeyboardEvent{Code: "Home"}}, // Home
    {"\x1b[F", KeyboardEvent{Code: "End"}}, // End
    {"\x1b[2~", KeyboardEvent{Code: "Insert"}}, // Insert
    {"\x1b[3~", KeyboardEvent{Code: "Delete"}}, // Delete
    {"\x1b[A", KeyboardEvent{Code: "Up"}}, // Up
    {"\x1b[B", KeyboardEvent{Code: "Down"}}, // Down
    {"\x1b[C", KeyboardEvent{Code: "Right"}}, // Right
    {"\x1b[D", KeyboardEvent{Code: "Left"}}, // Left
    // Ctrl
    {"\x1b[;5P", KeyboardEvent{Code: "F1", Ctrl: true}}, // Ctrl+F1
    {"\x1b[;5Q", KeyboardEvent{Code: "F2", Ctrl: true}}, // Ctrl+F2
    {"\x1b[;5R", KeyboardEvent{Code: "F3", Ctrl: true}}, // Ctrl+F3
    {"\x1b[;5S", KeyboardEvent{Code: "F4", Ctrl: true}}, // Ctrl+F4
    {"\x1b[15;5~", KeyboardEvent{Code: "F5", Ctrl: true}}, // Ctrl+F5
    {"\x1b[17;5~", KeyboardEvent{Code: "F6", Ctrl: true}}, // Ctrl+F6
    {"\x1b[18;5~", KeyboardEvent{Code: "F7", Ctrl: true}}, // Ctrl+F7
    {"\x1b[19;5~", KeyboardEvent{Code: "F8", Ctrl: true}}, // Ctrl+F8
    {"\x1b[20;5~", KeyboardEvent{Code: "F9", Ctrl: true}}, // Ctrl+F9
    {"\x1b[21;5~", KeyboardEvent{Code: "F10", Ctrl: true}}, // Ctrl+F10
    {"\x1b[23;5~", KeyboardEvent{Code: "F11", Ctrl: true}}, // Ctrl+F11
    {"\x1b[24;5~", KeyboardEvent{Code: "F12", Ctrl: true}}, // Ctrl+F12
    {"\x1b[5;5~", KeyboardEvent{Code: "PageUp", Ctrl: true}}, // Ctrl+PageUp
    {"\x1b[6;5~", KeyboardEvent{Code: "PageDown", Ctrl: true}}, // Ctrl+PageDown
    {"\x1b[1;5H", KeyboardEvent{Code: "Home", Ctrl: true}}, // Ctrl+Home
    {"\x1b[1;5F", KeyboardEvent{Code: "End", Ctrl: true}}, // Ctrl+End
    {"\x1b[2;5~", KeyboardEvent{Code: "Insert", Ctrl: true}}, // Ctrl+Insert
    {"\x1b[3;5~", KeyboardEvent{Code: "Delete", Ctrl: true}}, // Ctrl+Delete
    {"\x1b[1;5A", KeyboardEvent{Code: "Up", Ctrl: true}}, // Ctrl+Up
    {"\x1b[1;5B", KeyboardEvent{Code: "Down", Ctrl: true}}, // Ctrl+Down
    {"\x1b[1;5C", KeyboardEvent{Code: "Right", Ctrl: true}}, // Ctrl+Right
    {"\x1b[1;5D", KeyboardEvent{Code: "Left", Ctrl: true}}, // Ctrl+Left
    // Alt
    {"\x1b[;3P", KeyboardEvent{Code: "F1", Alt: true}}, // Alt+F1
    {"\x1b[;3Q", KeyboardEvent{Code: "F2", Alt: true}}, // Alt+F2
    {"\x1b[;3R", KeyboardEvent{Code: "F3", Alt: true}}, // Alt+F3
    {"\x1b[;3S", KeyboardEvent{Code: "F4", Alt: true}}, // Alt+F4
    {"\x1b[15;3~", KeyboardEvent{Code: "F5", Alt: true}}, // Alt+F5
    {"\x1b[17;3~", KeyboardEvent{Code: "F6", Alt: true}}, // Alt+F6
    {"\x1b[18;3~", KeyboardEvent{Code: "F7", Alt: true}}, // Alt+F7
    {"\x1b[19;3~", KeyboardEvent{Code: "F8", Alt: true}}, // Alt+F8
    {"\x1b[20;3~", KeyboardEvent{Code: "F9", Alt: true}}, // Alt+F9
    {"\x1b[21;3~", KeyboardEvent{Code: "F10", Alt: true}}, // Alt+F10
    {"\x1b[23;3~", KeyboardEvent{Code: "F11", Alt: true}}, // Alt+F11
    {"\x1b[24;3~", KeyboardEvent{Code: "F12", Alt: true}}, // Alt+F12
    {"\x1b[5;3~", KeyboardEvent{Code: "PageUp", Alt: true}}, // Alt+PageUp
    {"\x1b[6;3~", KeyboardEvent{Code: "PageDown", Alt: true}}, // Alt+PageDown
    {"\x1b[1;3H", KeyboardEvent{Code: "Home", Alt: true}}, // Alt+Home
    {"\x1b[1;3F", KeyboardEvent{Code: "End", Alt: true}}, // Alt+End
    {"\x1b[2;3~", KeyboardEvent{Code: "Insert", Alt: true}}, // Alt+Insert
    {"\x1b[3;3~", KeyboardEvent{Code: "Delete", Alt: true}}, // Alt+Delete
    {"\x1b[1;3A", KeyboardEvent{Code: "Up", Alt: true}}, // Alt+Up
    {"\x1b[1;3B", KeyboardEvent{Code: "Down", Alt: true}}, // Alt+Down
    {"\x1b[1;3C", KeyboardEvent{Code: "Right", Alt: true}}, // Alt+Right
    {"\x1b[1;3D", KeyboardEvent{Code: "Left", Alt: true}}, // Alt+Left
    // Shift
    {"\x1b[;2P", KeyboardEvent{Code: "F1"}}, // Shift+F1
    {"\x1b[;2Q", KeyboardEvent{Code: "F2"}}, // Shift+F2
    {"\x1b[;2R", KeyboardEvent{Code: "F3"}}, // Shift+F3
    {"\x1b[;2S", KeyboardEvent{Code: "F4"}}, // Shift+F4
    {"\x1b[15;2~", KeyboardEvent{Code: "F5"}}, // Shift+F5
    {"\x1b[17;2~", KeyboardEvent{Code: "F6"}}, // Shift+F6
    {"\x1b[18;2~", KeyboardEvent{Code: "F7"}}, // Shift+F7
    {"\x1b[19;2~", KeyboardEvent{Code: "F8"}}, // Shift+F8
    {"\x1b[20;2~", KeyboardEvent{Code: "F9"}}, // Shift+F9
    {"\x1b[21;2~", KeyboardEvent{Code: "F10"}}, // Shift+F10
    {"\x1b[23;2~", KeyboardEvent{Code: "F11"}}, // Shift+F11
    {"\x1b[24;2~", KeyboardEvent{Code: "F12"}}, // Shift+F12
    {"\x1b[5;2~", KeyboardEvent{Code: "PageUp"}}, // Shift+PageUp
    {"\x1b[6;2~", KeyboardEvent{Code: "PageDown"}}, // Shift+PageDown
    {"\x1b[1;2H", KeyboardEvent{Code: "Home"}}, // Shift+Home
    {"\x1b[1;2F", KeyboardEvent{Code: "End"}}, // Shift+End
    {"\x1b[2;2~", KeyboardEvent{Code: "Insert"}}, // Shift+Insert
    {"\x1b[3;2~", KeyboardEvent{Code: "Delete"}}, // Shift+Delete
    {"\x1b[1;2A", KeyboardEvent{Code: "Up"}}, // Shift+Up
    {"\x1b[1;2B", KeyboardEvent{Code: "Down"}}, // Shift+Down
    {"\x1b[1;2C", KeyboardEvent{Code: "Right"}}, // Shift+Right
    {"\x1b[1;2D", KeyboardEvent{Code: "Left"}}, // Shift+Left
    // Ctrl + Alt
    {"\x1b[;7P", KeyboardEvent{Code: "F1", Alt: true, Ctrl: true}}, // Ctrl+Alt+F1
    {"\x1b[;7Q", KeyboardEvent{Code: "F2", Alt: true, Ctrl: true}}, // Ctrl+Alt+F2
    {"\x1b[;7R", KeyboardEvent{Code: "F3", Alt: true, Ctrl: true}}, // Ctrl+Alt+F3
    {"\x1b[;7S", KeyboardEvent{Code: "F4", Alt: true, Ctrl: true}}, // Ctrl+Alt+F4
    {"\x1b[15;7~", KeyboardEvent{Code: "F5", Alt: true, Ctrl: true}}, // Ctrl+Alt+F5
    {"\x1b[17;7~", KeyboardEvent{Code: "F6", Alt: true, Ctrl: true}}, // Ctrl+Alt+F6
    {"\x1b[18;7~", KeyboardEvent{Code: "F7", Alt: true, Ctrl: true}}, // Ctrl+Alt+F7
    {"\x1b[19;7~", KeyboardEvent{Code: "F8", Alt: true, Ctrl: true}}, // Ctrl+Alt+F8
    {"\x1b[20;7~", KeyboardEvent{Code: "F9", Alt: true, Ctrl: true}}, // Ctrl+Alt+F9
    {"\x1b[21;7~", KeyboardEvent{Code: "F10", Alt: true, Ctrl: true}}, // Ctrl+Alt+F10
    {"\x1b[23;7~", KeyboardEvent{Code: "F11", Alt: true, Ctrl: true}}, // Ctrl+Alt+F11
    {"\x1b[24;7~", KeyboardEvent{Code: "F12", Alt: true, Ctrl: true}}, // Ctrl+Alt+F12
    {"\x1b[5;7~", KeyboardEvent{Code: "PageUp", Alt: true, Ctrl: true}}, // Ctrl+Alt+PageUp
    {"\x1b[6;7~", KeyboardEvent{Code: "PageDown", Alt: true, Ctrl: true}}, // Ctrl+Alt+PageDown
    {"\x1b[1;7H", KeyboardEvent{Code: "Home", Alt: true, Ctrl: true}}, // Ctrl+Alt+Home
    {"\x1b[1;7F", KeyboardEvent{Code: "End", Alt: true, Ctrl: true}}, // Ctrl+Alt+End
    {"\x1b[2;7~", KeyboardEvent{Code: "Insert", Alt: true, Ctrl: true}}, // Ctrl+Alt+Insert
    {"\x1b[3;7~", KeyboardEvent{Code: "Delete", Alt: true, Ctrl: true}}, // Ctrl+Alt+Delete
    {"\x1b[1;7A", KeyboardEvent{Code: "Up", Alt: true, Ctrl: true}}, // Ctrl+Alt+Up
    {"\x1b[1;7B", KeyboardEvent{Code: "Down", Alt: true, Ctrl: true}}, // Ctrl+Alt+Down
    {"\x1b[1;7C", KeyboardEvent{Code: "Right", Alt: true, Ctrl: true}}, // Ctrl+Alt+Right
    {"\x1b[1;7D", KeyboardEvent{Code: "Left", Alt: true, Ctrl: true}}, // Ctrl+Alt+Left
    // Ctrl + Shift
    {"\x1b[;6P", KeyboardEvent{Code: "F1", Ctrl: true}}, // Shift+Ctrl+F1
    {"\x1b[;6Q", KeyboardEvent{Code: "F2", Ctrl: true}}, // Shift+Ctrl+F2
    {"\x1b[;6R", KeyboardEvent{Code: "F3", Ctrl: true}}, // Shift+Ctrl+F3
    {"\x1b[;6S", KeyboardEvent{Code: "F4", Ctrl: true}}, // Shift+Ctrl+F4
    {"\x1b[15;6~", KeyboardEvent{Code: "F5", Ctrl: true}}, // Shift+Ctrl+F5
    {"\x1b[17;6~", KeyboardEvent{Code: "F6", Ctrl: true}}, // Shift+Ctrl+F6
    {"\x1b[18;6~", KeyboardEvent{Code: "F7", Ctrl: true}}, // Shift+Ctrl+F7
    {"\x1b[19;6~", KeyboardEvent{Code: "F8", Ctrl: true}}, // Shift+Ctrl+F8
    {"\x1b[20;6~", KeyboardEvent{Code: "F9", Ctrl: true}}, // Shift+Ctrl+F9
    {"\x1b[21;6~", KeyboardEvent{Code: "F10", Ctrl: true}}, // Shift+Ctrl+F10
    {"\x1b[23;6~", KeyboardEvent{Code: "F11", Ctrl: true}}, // Shift+Ctrl+F11
    {"\x1b[24;6~", KeyboardEvent{Code: "F12", Ctrl: true}}, // Shift+Ctrl+F12
    {"\x1b[5;6~", KeyboardEvent{Code: "PageUp", Ctrl: true}}, // Shift+Ctrl+PageUp
    {"\x1b[6;6~", KeyboardEvent{Code: "PageDown", Ctrl: true}}, // Shift+Ctrl+PageDown
    {"\x1b[1;6H", KeyboardEvent{Code: "Home", Ctrl: true}}, // Shift+Ctrl+Home
    {"\x1b[1;6F", KeyboardEvent{Code: "End", Ctrl: true}}, // Shift+Ctrl+End
    {"\x1b[2;6~", KeyboardEvent{Code: "Insert", Ctrl: true}}, // Shift+Ctrl+Insert
    {"\x1b[3;6~", KeyboardEvent{Code: "Delete", Ctrl: true}}, // Shift+Ctrl+Delete
    {"\x1b[1;6A", KeyboardEvent{Code: "Up", Ctrl: true}}, // Shift+Ctrl+Up
    {"\x1b[1;6B", KeyboardEvent{Code: "Down", Ctrl: true}}, // Shift+Ctrl+Down
    {"\x1b[1;6C", KeyboardEvent{Code: "Right", Ctrl: true}}, // Shift+Ctrl+Right
    {"\x1b[1;6D", KeyboardEvent{Code: "Left", Ctrl: true}}, // Shift+Ctrl+Left
    // Alt + Shift
    {"\x1b[;4P", KeyboardEvent{Code: "F1", Alt: true}}, // Shift+Alt+F1
    {"\x1b[;4Q", KeyboardEvent{Code: "F2", Alt: true}}, // Shift+Alt+F2
    {"\x1b[;4R", KeyboardEvent{Code: "F3", Alt: true}}, // Shift+Alt+F3
    {"\x1b[;4S", KeyboardEvent{Code: "F4", Alt: true}}, // Shift+Alt+F4
    {"\x1b[15;4~", KeyboardEvent{Code: "F5", Alt: true}}, // Shift+Alt+F5
    {"\x1b[17;4~", KeyboardEvent{Code: "F6", Alt: true}}, // Shift+Alt+F6
    {"\x1b[18;4~", KeyboardEvent{Code: "F7", Alt: true}}, // Shift+Alt+F7
    {"\x1b[19;4~", KeyboardEvent{Code: "F8", Alt: true}}, // Shift+Alt+F8
    {"\x1b[20;4~", KeyboardEvent{Code: "F9", Alt: true}}, // Shift+Alt+F9
    {"\x1b[21;4~", KeyboardEvent{Code: "F10", Alt: true}}, // Shift+Alt+F10
    {"\x1b[23;4~", KeyboardEvent{Code: "F11", Alt: true}}, // Shift+Alt+F11
    {"\x1b[24;4~", KeyboardEvent{Code: "F12", Alt: true}}, // Shift+Alt+F12
    {"\x1b[5;4~", KeyboardEvent{Code: "PageUp", Alt: true}}, // Shift+Alt+PageUp
    {"\x1b[6;4~", KeyboardEvent{Code: "PageDown", Alt: true}}, // Shift+Alt+PageDown
    {"\x1b[1;4H", KeyboardEvent{Code: "Home", Alt: true}}, // Shift+Alt+Home
    {"\x1b[1;4F", KeyboardEvent{Code: "End", Alt: true}}, // Shift+Alt+End
    {"\x1b[2;4~", KeyboardEvent{Code: "Insert", Alt: true}}, // Shift+Alt+Insert
    {"\x1b[3;4~", KeyboardEvent{Code: "Delete", Alt: true}}, // Shift+Alt+Delete
    {"\x1b[1;4A", KeyboardEvent{Code: "Up", Alt: true}}, // Shift+Alt+Up
    {"\x1b[1;4B", KeyboardEvent{Code: "Down", Alt: true}}, // Shift+Alt+Down
    {"\x1b[1;4C", KeyboardEvent{Code: "Right", Alt: true}}, // Shift+Alt+Right
    {"\x1b[1;4D", KeyboardEvent{Code: "Left", Alt: true}}, // Shift+Alt+Left
    // Ctrl + Alt + Shift
    {"\x1b[;8P", KeyboardEvent{Code: "F1", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F1
    {"\x1b[;8Q", KeyboardEvent{Code: "F2", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F2
    {"\x1b[;8R", KeyboardEvent{Code: "F3", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F3
    {"\x1b[;8S", KeyboardEvent{Code: "F4", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F4
    {"\x1b[15;8~", KeyboardEvent{Code: "F5", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F5
    {"\x1b[17;8~", KeyboardEvent{Code: "F6", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F6
    {"\x1b[18;8~", KeyboardEvent{Code: "F7", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F7
    {"\x1b[19;8~", KeyboardEvent{Code: "F8", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F8
    {"\x1b[20;8~", KeyboardEvent{Code: "F9", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F9
    {"\x1b[21;8~", KeyboardEvent{Code: "F10", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F10
    {"\x1b[23;8~", KeyboardEvent{Code: "F11", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F11
    {"\x1b[24;8~", KeyboardEvent{Code: "F12", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+F12
    {"\x1b[5;8~", KeyboardEvent{Code: "PageUp", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+PageUp
    {"\x1b[6;8~", KeyboardEvent{Code: "PageDown", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+PageDown
    {"\x1b[1;8H", KeyboardEvent{Code: "Home", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+Home
    {"\x1b[1;8F", KeyboardEvent{Code: "End", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+End
    {"\x1b[2;8~", KeyboardEvent{Code: "Insert", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+Insert
    {"\x1b[3;8~", KeyboardEvent{Code: "Delete", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+Delete
    {"\x1b[1;8A", KeyboardEvent{Code: "Up", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+Up
    {"\x1b[1;8B", KeyboardEvent{Code: "Down", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+Down
    {"\x1b[1;8C", KeyboardEvent{Code: "Right", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+Right
    {"\x1b[1;8D", KeyboardEvent{Code: "Left", Alt: true, Ctrl: true}}, // Shift+Ctrl+Alt+Left
    // Special Keys
    {"\x1b", KeyboardEvent{Code: "Escape"}}, // Escape
    {"\x1b ", KeyboardEvent{Code: "Space",Key: " ", Alt: true}}, // Alt+Space
    {" ", KeyboardEvent{Code: "Space",Key: " "}}, // Space
    {"\x00", KeyboardEvent{Code: "Space",Key: " ", Ctrl: true}}, // Ctrl+Space
    {"\x1b\x00", KeyboardEvent{Code: "Space",Key: " ", Alt: true, Ctrl: true}}, // Ctrl+Alt+Space
    {"\x1c", KeyboardEvent{Code: "\\", Ctrl: true}}, // Ctrl+\
    {"\x1d", KeyboardEvent{Code: "]", Ctrl: true}}, // Ctrl+]
    {"\t", KeyboardEvent{Code: "Tab"}}, // Tab
    {"\x1b[Z", KeyboardEvent{Code: "Tab"}}, // Shift+Tab
    {"\u007f", KeyboardEvent{Code: "Backspace"}}, // Backspace
    {"\b", KeyboardEvent{Code: "Backspace", Ctrl: true}}, // Ctrl+Backspace
    {"\x1b\u007f", KeyboardEvent{Code: "Backspace", Alt: true}}, // Alt+Backspace
    {"\x1b\b", KeyboardEvent{Code: "Backspace", Alt: true, Ctrl: true}}, // Ctrl+Alt+Backspace
    {"\r", KeyboardEvent{Code: "Return"}}, // Return
    {"\n", KeyboardEvent{Code: "Return", Ctrl: true}}, // Ctrl+Return
}
