// Code generated by "stringer -type StyleDisplay"; DO NOT EDIT.

package document

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DisplayInline-0]
	_ = x[DisplayBlock-1]
}

const _StyleDisplay_name = "DisplayInlineDisplayBlock"

var _StyleDisplay_index = [...]uint8{0, 13, 25}

func (i StyleDisplay) String() string {
	if i >= StyleDisplay(len(_StyleDisplay_index)-1) {
		return "StyleDisplay(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StyleDisplay_name[_StyleDisplay_index[i]:_StyleDisplay_index[i+1]]
}
